// [{postId, title, beans: [beanName, beanName, beanName], userId(작성자), createAt}]

export const BeanPostdb = [
  {
    postId: 1,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특맛과 단맛이 특맛과 단맛이 특맛과 단맛이 특징',
    beans: ['자바', '만델링'],
    userId: 'hihi',
    createAt: '2020-12-20',
  },
  {
    postId: 2,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['자바', '말라위 AAA+'],
    userId: 'nana',
    createAt: '2020-12-20',
  },
  {
    postId: 3,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'nana',
    createAt: '2020-12-20',
  },
  {
    postId: 4,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '자바'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
  {
    postId: 5,
    title: '쓴맛 속에 스며든 약간의 신맛과 단맛이 특징',
    beans: ['케냐 AA', '만델링'],
    userId: 'gugu',
    createAt: '2020-12-20',
  },
];
