export const Beandb = [
  {
    beanId: 1,
    beanName: '자바',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 3,
    bitterness: 2,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 2,
    beanName: '만델링',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 5,
    bitterness: 2,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 3,
    beanName: '발리 칸타마니',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 4,
    beanName: '가요 마운틴',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 4,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 5,
    beanName: '토라자',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 6,
    beanName: '몬순드 말리바',
    origin: '인도',
    fragrance: 5,
    acidity: 4,
    sweetness: 4,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 7,
    beanName: '슈프리모',
    origin: '콜롬비아',
    fragrance: 5,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 8,
    beanName: '엑셀소 디카페인',
    origin: '콜롬비아',
    fragrance: 5,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 9,
    beanName: '과테말라 SHB',
    origin: '과테말라',
    fragrance: 5,
    acidity: 4,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 10,
    beanName: '니카라과 SHB',
    origin: '니카라과',
    fragrance: 3,
    acidity: 4,
    sweetness: 3,
    bitterness: 3,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 11,
    beanName: '알투라 SHB',
    origin: '멕시코',
    fragrance: 4,
    acidity: 3,
    sweetness: 3,
    bitterness: 2,
    body: 2,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 12,
    beanName: '펜시 SHB',
    origin: '엘살바도르',
    fragrance: 4,
    acidity: 3,
    sweetness: 3,
    bitterness: 2,
    body: 2,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 13,
    beanName: '코스타리카 SHB',
    origin: '코스타리카',
    fragrance: 3,
    acidity: 3,
    sweetness: 4,
    bitterness: 3,
    body: 2,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 14,
    beanName: '파나마 SHB',
    origin: '파나마',
    fragrance: 5,
    acidity: 4,
    sweetness: 3,
    bitterness: 4,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 15,
    beanName: '도미니카 AA',
    origin: '도미니카',
    fragrance: 2,
    acidity: 4,
    sweetness: 3,
    bitterness: 2,
    body: 1,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 16,
    beanName: '산토스',
    origin: '브라질',
    fragrance: 4,
    acidity: 3,
    sweetness: 3,
    bitterness: 2,
    body: 2,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 17,
    beanName: '산토스 디카페인',
    origin: '브라질',
    fragrance: 4,
    acidity: 3,
    sweetness: 3,
    bitterness: 2,
    body: 2,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 18,
    beanName: 'SHG',
    origin: '온두라스',
    fragrance: 3,
    acidity: 4,
    sweetness: 2,
    bitterness: 2,
    body: 3,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 19,
    beanName: 'HB GRADE1',
    origin: '페루',
    fragrance: 5,
    acidity: 4,
    sweetness: 4,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 20,
    beanName: '예가체프',
    origin: '에디오피아',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 21,
    beanName: '시다모',
    origin: '모카',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 22,
    beanName: '르완다 AB+',
    origin: '르완다',
    fragrance: 2,
    acidity: 3,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 23,
    beanName: '말라위 AAA+',
    origin: '말라위',
    fragrance: 5,
    acidity: 3,
    sweetness: 3,
    bitterness: 4,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 24,
    beanName: '짐바브웨 AA+',
    origin: '짐바브웨',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 25,
    beanName: '케냐 AA',
    origin: '케냐',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    beanId: 26,
    beanName: '탄자니아 AA',
    origin: '탄자니아',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
