// GET /bean/all-beans
// TODO 추가 필요사항
//* like : false (boolean)
//* likeCount : 20 (사람들이 like한 숫자)
//* desc(원두 설명도 추가 필요) => 이후 예찬님이 진행 예정

export const Beandb = [
  {
    beanId: 1,
    beanName: '자바',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 3,
    bitterness: 2,
    body: 4,
    beanImage: '/asset/beans/bean4.jpg',
    desc: '원두에 대한 설명입니다',
    like: true,
    likeCount: 20,
  },
  {
    beanId: 2,
    beanName: '만델링',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 5,
    bitterness: 2,
    body: 4,
    beanImage: '/asset/beans/bean6.jpg',
    desc: '!!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~',
    like: true,
    likeCount: 0,
  },
  {
    beanId: 3,
    beanName: '발리 칸타마니',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 2,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: '/asset/beans/bean6.jpg',
    desc: '!!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~',
    like: false,
    likeCount: 0,
  },
  {
    beanId: 4,
    beanName: '가요 마운틴',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 4,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: '/asset/beans/bean6.jpg',
    desc: '!!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~',
    like: false,
    likeCount: 20,
  },
  {
    beanId: 5,
    beanName: '토라자',
    origin: '인도네시아',
    fragrance: 4,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 4,
    beanImage: '/asset/beans/bean1.jpg',
    desc: '!!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~',

    like: true,
    likeCount: 20,
  },
  {
    beanId: 6,
    beanName: '몬순드 말리바',
    origin: '인도',
    fragrance: 5,
    acidity: 4,
    sweetness: 4,
    bitterness: 3,
    body: 4,
    beanImage: '/asset/beans/bean1.jpg',
    like: true,
    likeCount: 20,
  },
  {
    beanId: 7,
    beanName: '슈프리모',
    origin: '콜롬비아',
    fragrance: 5,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: '/asset/beans/bean1.jpg',
    like: false,
    likeCount: 15,
  },
  {
    beanId: 8,
    beanName: '엑셀소 디카페인',
    origin: '콜롬비아',
    fragrance: 5,
    acidity: 5,
    sweetness: 3,
    bitterness: 2,
    body: 3,
    beanImage: '/asset/beans/bean1.jpg',
    like: false,
    likeCount: 15,
  },
  {
    beanId: 9,
    beanName: '과테말라 SHB',
    origin: '과테말라',
    fragrance: 5,
    acidity: 4,
    sweetness: 3,
    bitterness: 3,
    body: 4,
    beanImage: '/asset/beans/bean3.jpg',
    like: true,
    likeCount: 20,
  },
  {
    beanId: 10,
    beanName: '니카라과 SHB',
    origin: '니카라과',
    fragrance: 3,
    acidity: 4,
    sweetness: 3,
    bitterness: 3,
    body: 3,
    beanImage: '/asset/beans/bean3.jpg',
    like: false,
    likeCount: 30,
  },
];
